EnableInputFeedbackSounds 0
Gdk/UnscaledDPI 147456
Gdk/WindowScalingFactor 2
Gtk/ButtonImages 1
Gtk/CursorThemeName "default"
Gtk/CursorThemeSize 36
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/EnableAnimations 1
Gtk/FontName "JetBrainsMono Nerd Font,  10"
Gtk/MenuImages 1
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Net/CursorBlink 1
Net/CursorBlinkTime 1000
Net/EnableEventSounds 1
Net/IconThemeName "TokyoNight-SE"
Net/SoundThemeName "ocean"
Net/ThemeName "Tokyonight-Dark"
Xft/Antialias 1
Xft/HintStyle "hintslight"
Xft/Hinting 1
Xft/RGBA "rgb"
