general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 180
    on-timeout = tlp-stat -m | grep -q "BAT" && brightnessctl -sd intel_backlight set 10
    on-resume = tlp-stat -m | grep -q "BAT" && brightnessctl -rd intel_backlight
}

listener {
    timeout = 180
    on-timeout = tlp-stat -m | grep -q "BAT" && brightnessctl -sd platform:kbd_backlight set 0
    on-resume = tlp-stat -m | grep -q "BAT" && brightnessctl -rd platform:kbd_backlight
}

listener {
    timeout = 300
    on-timeout = tlp-stat -m | grep -q "BAT" && loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = tlp-stat -m | grep -q "BAT" && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = tlp-stat -m | grep -q "BAT" && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' brightnessctl -rd intel_backlight
}

listener {
    timeout = 1800
    on-timeout = tlp-stat -m | grep -q "BAT" && systemctl suspend
  }
